# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_COMPONENT_INSTALL "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/zenguyen/forks/rocPRIM;/home/zenguyen/forks/rocPRIM")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "devel;clients;tests")
set(CPACK_COMPONENTS_ALL_SET_BY_USER "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_CLIENTS_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_CLIENTS_PACKAGE_DEPENDS "rocprim-tests-static (>= 3.3.0)")
set(CPACK_DEBIAN_CLIENTS_PACKAGE_NAME "rocprim-clients-static")
set(CPACK_DEBIAN_COMPRESSION_TYPE "xz")
set(CPACK_DEBIAN_DEVEL_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_DEVEL_PACKAGE_NAME "rocprim-dev")
set(CPACK_DEBIAN_DEVEL_PACKAGE_PROVIDES "CPACK_DEBIAN_PACKAGE_PROVIDES, rocprim (= 3.3.0)")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "amd64")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/home/zenguyen/forks/rocPRIM/debian/postinst;/home/zenguyen/forks/rocPRIM/debian/prerm")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "hip-static-dev (>= 4.5.0), rocm-core")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "rocPRIM Maintainer <rocprim-maintainer@amd.com>")
set(CPACK_DEBIAN_PACKAGE_RELEASE "3c4663e6~dirty")
set(CPACK_DEBIAN_PACKAGE_SECTION "devel")
set(CPACK_DEBIAN_RUNTIME_PACKAGE_RECOMMENDS "rocprim-dev (>=3.3.0)")
set(CPACK_DEBIAN_TESTS_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_TESTS_PACKAGE_NAME "rocprim-tests-static")
set(CPACK_DEB_COMPONENT_INSTALL "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "rocprim built using CMake")
set(CPACK_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_INSTALLED_DIRECTORIES "/home/zenguyen/forks/rocPRIM;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/opt/rocm")
set(CPACK_MODULE_PATH "/home/zenguyen/forks/rocPRIM/cmake;/opt/rocm/lib/cmake/hip;/cmake;/opt/rocm/lib/cmake/hip;/opt/rocm/hip/cmake;/opt/rocm/share/rocmcmakebuildtools/cmake;/opt/rocm/share/rocmcmakebuildtools/cmake")
set(CPACK_NSIS_DISPLAY_NAME "rocprim 3.3.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_MODIFY_PATH "ON")
set(CPACK_NSIS_PACKAGE_NAME "rocprim")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/llvm-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/llvm-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/zenguyen/forks/rocPRIM/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Radeon Open Compute Parallel Primitives Library")
set(CPACK_PACKAGE_FILE_NAME "rocprim-3.3.0-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "rocprim 3.3.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "rocprim 3.3.0")
set(CPACK_PACKAGE_NAME "rocprim")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Advanced Micro Devices, Inc")
set(CPACK_PACKAGE_VERSION "3.3.0")
set(CPACK_PACKAGE_VERSION_MAJOR "3")
set(CPACK_PACKAGE_VERSION_MINOR "3")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PACKAGING_INSTALL_PREFIX "")
set(CPACK_PACKAGING_INSTALL_PREFIX "")
set(CPACK_READELF_EXECUTABLE "/usr/bin/llvm-readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/zenguyen/forks/rocPRIM/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "/usr/local/share/cmake-3.25/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/share/cmake-3.25/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_CLIENTS_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_CLIENTS_PACKAGE_NAME "rocprim-clients-static")
set(CPACK_RPM_CLIENTS_PACKAGE_REQUIRES "rocprim-tests-static >= 3.3.0")
set(CPACK_RPM_COMPONENT_INSTALL "ON")
set(CPACK_RPM_DEVEL_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_DEVEL_PACKAGE_NAME "rocprim-devel")
set(CPACK_RPM_DEVEL_PACKAGE_PROVIDES "CPACK_DEBIAN_PACKAGE_PROVIDES, rocprim = 3.3.0")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "${CPACK_PACKAGING_INSTALL_PREFIX}")
set(CPACK_RPM_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_PACKAGE_AUTOREQPROV "Off")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_NAME "rocprim")
set(CPACK_RPM_PACKAGE_RELEASE "3c4663e6_dirty")
set(CPACK_RPM_PACKAGE_RELOCATABLE "Off")
set(CPACK_RPM_PACKAGE_REQUIRES "hip-static-devel >= 4.5.0, rocm-core")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "/home/zenguyen/forks/rocPRIM/debian/postinst")
set(CPACK_RPM_PRE_UNINSTALL_SCRIPT_FILE "/home/zenguyen/forks/rocPRIM/debian/prerm")
set(CPACK_RPM_RUNTIME_PACKAGE_SUGGESTS "rocprim-devel >= 3.3.0")
set(CPACK_RPM_TESTS_FILE_NAME "RPM-DEFAULT")
set(CPACK_RPM_TESTS_PACKAGE_NAME "rocprim-tests-static")
set(CPACK_SET_DESTDIR "ON")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_IGNORE_FILES "/CVS/;/\\.svn/;/\\.bzr/;/\\.hg/;/\\.git/;\\.swp\$;\\.#;/#")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/zenguyen/forks/rocPRIM;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/zenguyen/forks/rocPRIM/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "rocprim-3.3.0-Source")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "0")
set(CPACK_TOPLEVEL_TAG "Linux-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/zenguyen/forks/rocPRIM/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
